.TH "YESVGMAP" "1" "April 2023" "Yesvgmap v0.3.14" "User Commands"
.SH NAME
Yesvgmap \- Manual page for yesvgmap v0.3.14.
.SH DESCRIPTION
Generate SVG sprite maps from individual SVG images.
.SS USAGE:
.TP
yesvgmap [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-\-hidden\fR
Hide the map using the 'hidden' HTML attribute. This takes priority over \-\-offscreen when both are present.
.TP
\fB\-\-offscreen\fR
Hide the map using inline styles to position it offscreen.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) file and/or directory paths from this text file, one entry per line.
.TP
\fB\-\-map\-class\fR <CLASS>
Add this class to the generated SVG map. [default: ]
.TP
\fB\-\-map\-id\fR <ID>
Add this ID to the generated SVG map. [default: ]
.TP
\fB\-o\fR, \fB\-\-output\fR <FILE>
Save the generated map to this location. If omitted, the map will print to STDOUT instead.
.TP
\fB\-p\fR, \fB\-\-prefix\fR <PREFIX>
Set a custom prefix for the IDs of each entry in the map. (IDs look like PREFIX\-STEM, where STEM is the alphanumeric portion of the source file name, e.g. 'i\-close'.) [default: i]
.SS <PATH(S)…>:
.TP
One or more file and/or directory paths to crunch and/or (recursively) crawl. Only files with the extension .svg will ultimately be included.
