.TH "YESVGMAP" "1" "May 2025" "yesvgmap v0.7.0" "User Commands"
.SH NAME
YESVGMAP \- Manual page for yesvgmap v0.7.0.
.SH DESCRIPTION
Generate SVG sprite maps from individual SVG images.
.SS USAGE:
.TP
yesvgmap [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-a\fR, \fB\-\-attribute\fR <KEY[=VAL]>
Add an attribute — id, class, etc. — to the top\-level <svg> element.
.TP
\fB\-l\fR, \fB\-\-list\fR <PATH>
Read (absolute) file and/or directory paths from this text file — or STDIN if '\-' — one entry per line, instead of or in addition to any trailing <PATH(S)>.
.TP
\fB\-o\fR, \fB\-\-output\fR <PATH>
Save the generated map to this location. If omitted, the map will print to STDOUT instead.
.TP
\fB\-p\fR, \fB\-\-prefix\fR <PREFIX>
Set a custom prefix for the IDs of each entry in the map. (IDs look like PREFIX\-STEM, where STEM is the alphanumeric portion of the source file name, e.g. 'i\-close'.) [default: i]
.SS TRAILING:
.TP
\fB<PATH(s)…>\fR
One or more file and/or directory paths to crunch and/or (recursively) crawl. Only files with the extension .svg will ultimately be included.
