.TH "YESVGMAP" "1" "January 2022" "Yesvgmap v0.2.5" "User Commands"
.SH NAME
Yesvgmap \- Manual page for yesvgmap v0.2.5.
.SH DESCRIPTION
Yesvgmap is a CLI tool for building SVG sprite maps from individual SVG images.
.SS USAGE:
.TP
yesvgmap [FLAGS] [OPTIONS] <SVG(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-hidden\fR
Hide with the 'hidden' attribute. Overrides \-\-offscreen if both are set.
.TP
\fB\-\-offscreen\fR
Hide by placing the element offscreen with inline styles.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print application version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.TP
\fB\-\-map\-class\fR <CLASS>
A class attribute value to assign to the map itself. [default: ]
.TP
\fB\-\-map\-id\fR <ID>
An ID attribute value to assign to the map itself. [default: ]
.TP
\fB\-o\fR, \fB\-\-output\fR <FILE>
A file path to save the generated map to. If not specified, the map will print to STDOUT.
.TP
\fB\-p\fR, \fB\-\-prefix\fR <PREFIX>
Symbols will be assigned the ID 'prefix\-basename'. [default: icon]
.SS <SVG(S)…>:
.TP
Any number of files and directories to crawl and crunch.
